apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdA== # root
  mysql-database: ZGJ0ZWNoY2hhbGxhbmdl # dbtechchallange
  mysql-user: dHVybWFmaWFw # turmafiap
  mysql-password: UGFzc3dvcmQxMjM= # Password123
