name: Deploy Code to EKS cluster

on:
  push:
    branches:
      - main
  
  workflow_dispatch:


env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_DEFAULT_REGION: 'us-east-1'

jobs:
  kubernetes:
    runs-on: ubuntu-latest

    steps:
      - name: update-kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name techchallenge-eks-cluster
      
      - name: apply kubernetes 
        run: |
          kubectl apply -f ./Kubernetes/