name: Update Code and rollout new changes to EKS cluster

on:
  push:
    branches:
      - main
      - gihub-action
  
  workflow_dispatch:


env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_DEFAULT_REGION: 'us-east-1'

jobs:
  kubernetes:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      # Build application and release image to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup DockerBuildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: axelkjellin/pedido:latest

      # Deploy application to EKS cluster
      - name: update-kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name techchallenge-eks-cluster
      
      - name: rollout-kubernetes 
        run: |
          ubectl rollout restart deployment java-app-deployment 